#!/bin/bash


case $1 in
	vissenlampaan)
		ssh pi@192.168.178.70 ./lamp1aan.sh ;;
	vissenlampuit)
		ssh pi@192.168.178.70 ./lamp1uit.sh ;;
	woonkamerlampaan)
		ssh pi@192.168.178.70 ./lamp2aan.sh ;;
	woonkamerlampuit)
		ssh pi@192.168.178.70 ./lamp2uit.sh ;;
	tvschakelaaraan)
		ssh pi@192.168.178.70 ./lamp3aan.sh ;;
	tvschakelaaruit)
		ssh pi@192.168.178.70 ./lamp3uit.sh ;;
	waterkokeraan)
		ssh pi@192.168.178.70 ./waterkoker.sh ;;
	waterkokeruit)
		ssh pi@192.168.178.70 ./waterkokeruit.sh ;;
	tvaan)
		ssh pi@192.168.178.11 "echo 'on 0' |cec-client -s -d 1" ;;
	tvuit)
		ssh pi@192.168.178.11 "echo 'standby 0' |cec-client -s -d 1" ;;	
	kodiplay)
		curl -H "Accept: application/json" -H "Content-Type: application/json" --data {"jsonrpc": "2.0", "method": "Player.PlayPause", "params": { "playerid": 0 }, "id": 1}
esac
